development:
  adapter: postgresql
  encoding: unicode  
  database: dicemasters_development
  username: postgres
  password: dicemasters
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: dicemasters_test
  pool: 5
  username: postgres
  password: dicemasters

production:
  adapter: postgresql
  encoding: unicode
  database: dicemasters_test
  pool: 5
  username: postgres
  password: dicemasters
