development:
  adapter: postgresql
  encoding: unicode  
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: postgres
  password: dicemasters

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: postgres
  password: dicemasters
